
"""
Created on Sat Dec 30 10:51:22 2017

@author: Sarbadal.Pal
"""
import pandas as pd
from sklearn import neighbors as n

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
def BOS_KDTree_def(data=None, test=None, control=None, vcn=None, var2pickneighbors=None,                                                                                                                                           #
                   Identifier = 'Store', Cluster = 'Cluster', Changed = 'Changed', Test = 'Test'):                                                                                                                                 #
  #create a empty DataFrame.....                                                                                                                                                                                                   #
  test_control_df = pd.DataFrame()                                                                                                                                                                                                 #
  req_col_list = [Identifier, Cluster, Test, Changed]                                                                                                                                                                              #
  req_col_list.extend(var2pickneighbors)                                                                                                                                                                                           #
  replacement = 'T'                                                                                                                                                                                                                #
  no_of_control = len(control)                                                                                                                                                                                                     #
                                                                                                                                                                                                                                   #
######################################################################################################################################                                                                                             #
  if replacement.upper() == 'T':                                                                                                   ###                                                                                             #
    tmp_dic = {}                                                                                                                   ###                                                                                             #
                                                                                                                                   ###                                                                                             #
    for i in range(1, no_of_control+1):                                                                                            ###                                                                                             #
      df_name = 'tmp_df_' + str(i)                                                                                                 ###                                                                                             #
      tmp_dic[df_name] = test.copy()                                                                                               ###                                                                                             #
      dist, ind = [99.00, i-1]                                                                                                     ###                                                                                             #
                                                                                                                                   ###                                                                                             #
      control_ID = control[control.index == ind]['Identifier'].tolist()[0]                                                         ###                                                                                             #
      tmp_dic[df_name]['Control_ID'] = control_ID                                                                                  ###                                                                                             #
      tmp_dic[df_name]['TtoC_Dist'] = dist                                                                                         ###                                                                                             #
  ####################################################################################################################################                                                                                             #
  df_list = []                                                                                                                     ###                                                                                             #
  for i in range(1, no_of_control+1):                                                                                              ###                                                                                             #
    df_name = 'tmp_df_' + str(i)                                                                                                   ###                                                                                             #
    df_list.append(tmp_dic[df_name])                                                                                               ###                                                                                             #
  test_control_df = pd.concat([df for df in df_list], ignore_index=True)                                                           ###                                                                                             #
  c_list = ['Identifier']                                                                                                          ###                                                                                             #
  c_list.extend(var2pickneighbors)                                                                                                 ###                                                                                             #
  rename_dic = {}                                                                                                                  ###                                                                                             #
  for c in var2pickneighbors:                                                                                                      ###                                                                                             #
    rename_dic[c] = 'C_'+c                                                                                                         ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  test_control_df = pd.merge(test_control_df, data[c_list].rename(columns=rename_dic).rename(columns={'Identifier':'Store'}),      ###                                                                                             #
                             how='left', left_on='Control_ID', right_on='Store',                                                   ###                                                                                             #
                             left_index=False, right_index=False, sort=False).drop(['Store'], axis=1).copy()                       ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  col_name = req_col_list.copy()                                                                                                   ###                                                                                             #
  col_name.extend(['C_'+itm for itm in var2pickneighbors])                                                                         ###                                                                                             #
  col_name.extend(['Control_ID','TtoC_Dist'])                                                                                      ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  field_name = []                                                                                                                  ###                                                                                             #
  for field in col_name:                                                                                                           ###                                                                                             #
    if field == Identifier: field_name.append('Identifier')                                                                        ###                                                                                             #
    else: field_name.append(field)                                                                                                 ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  test_control_df = test_control_df[field_name]                                                                                    ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  min_count = test_control_df.groupby(['Identifier'])['Identifier'].count().min()                                                  ###                                                                                             #
  test_control_df = test_control_df.sort_values(by=['Identifier','Control_ID'], ascending=[True, True])                            ###                                                                                             #
  test_control_df.reset_index(drop=True, inplace=True)                                                                             ###                                                                                             #
  test_control_df['Counter'] = 1                                                                                                   ###                                                                                             #
  test_control_df['Cum_Count'] = test_control_df.groupby(['Identifier'])['Counter'].cumsum()                                       ###                                                                                             #
  test_control_df['Min_Count'] = min_count                                                                                         ###                                                                                             #
  test_control_df = test_control_df.loc[test_control_df['Min_Count']>=test_control_df['Cum_Count']].copy()                         ###                                                                                             #
  test_control_df.drop(['Min_Count','Counter','Cum_Count'], axis=1, inplace=True)                                                  ###                                                                                             #
  test_control_df.reset_index(drop=True, inplace=True)                                                                             ###                                                                                             #
                                                                                                                                                                                                                                   #
  return test_control_df                                                                                                                                                                                                           #
                                                                                                                                                                                                                                   #
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#