
"""
Created on Sat Dec 30 10:51:22 2017

@author: Sarbadal.Pal
"""
import pandas as pd
from sklearn import neighbors as n

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
def KDTree_def(data=None, test=None, control=None, vcn=None, var2pickneighbors=None, no_of_control=10, replacement='T',                                                                                                            #
               Identifier = 'Store', Cluster = 'Cluster', Changed = 'Changed', Test = 'Test'):                                                                                                                                     #
  #create a empty DataFrame.....                                                                                                                                                                                                   #
  test_control_df = pd.DataFrame()                                                                                                                                                                                                 #
  req_col_list = [Identifier, Cluster, Test, Changed]                                                                                                                                                                              #
  req_col_list.extend(var2pickneighbors)                                                                                                                                                                                           #
                                                                                                                                                                                                                                   #
  if no_of_control == None: no_of_control = len(control)                                                                                                                                                                           #
  if (replacement.upper() != 'T') & (no_of_control < len(control)):                                                                                                                                                                #
    no_of_control = min(no_of_control, int(len(control)/no_of_control))                                                                                                                                                            #
  if (replacement.upper() != 'T') & (no_of_control >= len(control)):                                                                                                                                                               #
    no_of_control = min(no_of_control, int(len(control)/len(test)))                                                                                                                                                                #
  no_of_control = min(no_of_control, len(control))                                                                                                                                                                                 #
                                                                                                                                                                                                                                   #
  if no_of_control < len(control):                                                                                                                                                                                                 #
  ######################################################################################################################################                                                                                           #
    if replacement.upper() == 'T':                                                                                                   ###                                                                                           #
      tmp_dic = {}                                                                                                                   ###                                                                                           #
      test_list = test['Identifier'].tolist()                                                                                        ###                                                                                           #
      df_tree = data[-data['Identifier'].isin(test_list)].copy()                                                                     ###                                                                                           #
      df_tree.reset_index(drop=True, inplace=True)                                                                                   ###                                                                                           #
      tree = n.KDTree(df_tree[vcn], leaf_size=len(vcn))                                                                              ###                                                                                           #
                                                                                                                                     ###                                                                                           #
      for i in range(1, no_of_control+1):                                                                                            ###                                                                                           #
        df_name = 'tmp_df_' + str(i)                                                                                                 ###                                                                                           #
        tmp_dic[df_name] = test.copy()                                                                                               ###                                                                                           #
                                                                                                                                     ###                                                                                           #
        for r in range(0, len(test)):                                                                                                ###                                                                                           #
          ID = test['Identifier'][r]                                                                                                 ###                                                                                           #
          Index = test.loc[test['Identifier']==ID][vcn].copy()                                                                       ###                                                                                           #
          dist, ind = tree.query(Index, k=i+0)                                                                                       ###                                                                                           #
          dist, ind = dist[0][i-1], ind[0][i-1]                                                                                      ###                                                                                           #
                                                                                                                                     ###                                                                                           #
          control_ID = df_tree[df_tree.index == ind]['Identifier']                                                                   ###                                                                                           #
          tmp_dic[df_name].loc[test['Identifier'] == ID, 'Control_ID'] = control_ID.tolist()[0]                                      ###                                                                                           #
          tmp_dic[df_name].loc[test['Identifier'] == ID, 'TtoC_Dist'] = dist                                                         ###                                                                                           #
    ####################################################################################################################################                                                                                           #
    if replacement.upper() == 'F':                                                                                                   ###                                                                                           #
      tmp_dic = {}                                                                                                                   ###                                                                                           #
      test_list = test['Identifier'].tolist()                                                                                        ###                                                                                           #
      for i in range(1,no_of_control+1):                                                                                             ###                                                                                           #
        df_name = 'tmp_df_' + str(i)                                                                                                 ###                                                                                           #
        tmp_dic[df_name] = test.copy()                                                                                               ###                                                                                           #
        df_to_cal_tree = data.copy()                                                                                                 ###                                                                                           #
                                                                                                                                     ###                                                                                           #
        if len(df_to_cal_tree)>=len(test):                                                                                           ###                                                                                           #
          for r in range(0, len(test)):                                                                                              ###                                                                                           #
            df_to_cal_tree = data[-data['Identifier'].isin(test_list)].copy()                                                        ###                                                                                           #
            df_to_cal_tree.reset_index(drop=True, inplace=True)                                                                      ###                                                                                           #
                                                                                                                                     ###                                                                                           #
            if len(df_to_cal_tree)>=i+0:                                                                                             ###                                                                                           #
              ID = test['Identifier'][r]                                                                                             ###                                                                                           #
              Index = test.loc[test['Identifier']==ID][vcn].copy()                                                                   ###                                                                                           #
              tree = n.KDTree(df_to_cal_tree[vcn], leaf_size=len(vcn))                                                               ###                                                                                           #
              dist, ind = tree.query(Index, k=i+0)                                                                                   ###                                                                                           #
              dist, ind = dist[0][i-1], ind[0][i-1]                                                                                  ###                                                                                           #
                                                                                                                                     ###                                                                                           #
              control_ID = df_to_cal_tree[df_to_cal_tree.index == ind]['Identifier']                                                 ###                                                                                           #
              tmp_dic[df_name].loc[test['Identifier'] == ID, 'Control_ID'] = control_ID.tolist()[0]                                  ###                                                                                           #
              tmp_dic[df_name].loc[test['Identifier'] == ID, 'TtoC_Dist'] = dist                                                     ###                                                                                           #
              test_list.append(control_ID.tolist()[0])                                                                               ###                                                                                           #
    ####################################################################################################################################                                                                                           #
  else:                                                                                                                                                                                                                            #
    if replacement.upper() == 'T':                                                                                                                                                                                                 #
      tmp_dic = {}                                                                                                                   ###                                                                                           #
                                                                                                                                     ###                                                                                           #
      for i in range(1, no_of_control+1):                                                                                            ###                                                                                           #
        df_name = 'tmp_df_' + str(i)                                                                                                 ###                                                                                           #
        tmp_dic[df_name] = test.copy()                                                                                               ###                                                                                           #
        dist, ind = [99.00, i-1]                                                                                                     ###                                                                                           #
                                                                                                                                     ###                                                                                           #
        control_ID = control[control.index == ind]['Identifier'].tolist()[0]                                                         ###                                                                                           #
        tmp_dic[df_name]['Control_ID'] = control_ID                                                                                  ###                                                                                           #
        tmp_dic[df_name]['TtoC_Dist'] = dist                                                                                         ###                                                                                           #
  ######################################################################################################################################                                                                                           #
    if replacement.upper() == 'F':                                                                                                                                                                                                 #
      tmp_dic = {}                                                                                                                   ###                                                                                           #
      test_list = test['Identifier'].tolist()                                                                                        ###                                                                                           #
      for i in range(1,no_of_control+1):                                                                                             ###                                                                                           #
        df_name = 'tmp_df_' + str(i)                                                                                                 ###                                                                                           #
        tmp_dic[df_name] = test.copy()                                                                                               ###                                                                                           #
        df_to_cal_tree = data.copy()                                                                                                 ###                                                                                           #
                                                                                                                                     ###                                                                                           #
        if len(df_to_cal_tree)>=len(test):                                                                                           ###                                                                                           #
          for r in range(0, len(test)):                                                                                              ###                                                                                           #
            df_to_cal_tree = data[-data['Identifier'].isin(test_list)].copy()                                                        ###                                                                                           #
            df_to_cal_tree.reset_index(drop=True, inplace=True)                                                                      ###                                                                                           #
                                                                                                                                     ###                                                                                           #
            if len(df_to_cal_tree)>=i+0:                                                                                             ###                                                                                           #
              ID = test['Identifier'][r]                                                                                             ###                                                                                           #
              Index = test.loc[test['Identifier']==ID][vcn].copy()                                                                   ###                                                                                           #
              tree = n.KDTree(df_to_cal_tree[vcn], leaf_size=len(vcn))                                                               ###                                                                                           #
              dist, ind = tree.query(Index, k=i+0)                                                                                   ###                                                                                           #
              dist, ind = dist[0][i-1], ind[0][i-1]                                                                                  ###                                                                                           #
                                                                                                                                     ###                                                                                           #
              control_ID = df_to_cal_tree[df_to_cal_tree.index == ind]['Identifier']                                                 ###                                                                                           #
              tmp_dic[df_name].loc[test['Identifier'] == ID, 'Control_ID'] = control_ID.tolist()[0]                                  ###                                                                                           #
              tmp_dic[df_name].loc[test['Identifier'] == ID, 'TtoC_Dist'] = dist                                                     ###                                                                                           #
              test_list.append(control_ID.tolist()[0])                                                                               ###                                                                                           #
                                                                                                                                                                                                                                   #
  ####################################################################################################################################                                                                                             #
                                                                                                                                   ###                                                                                             #
  df_list = []                                                                                                                     ###                                                                                             #
  for i in range(1, no_of_control+1):                                                                                              ###                                                                                             #
    df_name = 'tmp_df_' + str(i)                                                                                                   ###                                                                                             #
    df_list.append(tmp_dic[df_name])                                                                                               ###                                                                                             #
  test_control_df = pd.concat([df for df in df_list], ignore_index=True)                                                           ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  c_list = ['Identifier']                                                                                                          ###                                                                                             #
  c_list.extend(var2pickneighbors)                                                                                                 ###                                                                                             #
  rename_dic = {}                                                                                                                  ###                                                                                             #
  for c in var2pickneighbors:                                                                                                      ###                                                                                             #
    rename_dic[c] = 'C_'+c                                                                                                         ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  test_control_df = pd.merge(test_control_df, data[c_list].rename(columns=rename_dic).rename(columns={'Identifier':'Store'}),      ###                                                                                             #
                             how='left', left_on='Control_ID', right_on='Store',                                                   ###                                                                                             #
                             left_index=False, right_index=False, sort=False).drop(['Store'], axis=1).copy()                       ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  col_name = req_col_list.copy()                                                                                                   ###                                                                                             #
  col_name.extend(['C_'+itm for itm in var2pickneighbors])                                                                         ###                                                                                             #
  col_name.extend(['Control_ID','TtoC_Dist'])                                                                                      ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  field_name = []                                                                                                                  ###                                                                                             #
  for field in col_name:                                                                                                           ###                                                                                             #
    if field == Identifier: field_name.append('Identifier')                                                                        ###                                                                                             #
    else: field_name.append(field)                                                                                                 ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  test_control_df = test_control_df[field_name]                                                                                    ###                                                                                             #
                                                                                                                                   ###                                                                                             #
  min_count = test_control_df.groupby(['Identifier'])['Identifier'].count().min()                                                  ###                                                                                             #
  test_control_df = test_control_df.sort_values(by=['Identifier','TtoC_Dist'], ascending=[True, True])                             ###                                                                                             #
  test_control_df.reset_index(drop=True, inplace=True)                                                                             ###                                                                                             #
  test_control_df['Counter'] = 1                                                                                                   ###                                                                                             #
  test_control_df['Cum_Count'] = test_control_df.groupby(['Identifier'])['Counter'].cumsum()                                       ###                                                                                             #
  test_control_df['Min_Count'] = min_count                                                                                         ###                                                                                             #
  test_control_df = test_control_df.loc[test_control_df['Min_Count']>=test_control_df['Cum_Count']].copy()                         ###                                                                                             #
  test_control_df.drop(['Min_Count','Counter','Cum_Count'], axis=1, inplace=True)                                                  ###                                                                                             #
  test_control_df.reset_index(drop=True, inplace=True)                                                                             ###                                                                                             #
                                                                                                                                                                                                                                   #
  return [test_control_df, min_count]                                                                                                                                                                                              #
                                                                                                                                                                                                                                   #
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
